### ISSUE TITLE
moar functions

### ISSUE THREAD

**Issue by nicolas-t** [romuleald/toggler#3]
Why not creating functions ? like `open`, `close`, `closeAll`, `closeOther`, `destroy`/ `teardown`   ...
The code would be more readable.

Why is the selector function called selector ? `'.JS_toggler'` is the jQuery selector while selector is the event handler, it's confusing.

Also it would be better with namespaced events:  
`$allLinksToggler.on('click.toggler open.toggler close.toggler toggle.toggler', selector);`  
(see: https://css-tricks.com/namespaced-events-jquery/)

**Comment by nicolas-t** [comment]
What about passing a custom css selector instead of `'.JS_toggler'` when calling `init()` ?

**Comment by romuleald** [comment]
solved in 21178cd
